### ISSUE TITLE
Getting error on select query in javascript as Unhandled Exception: System.InvalidOperationException: The 'VFPOLEDB.1' provider is not registered on the local machine.?

### ISSUE THREAD

**Issue by amruta21** [rabrux/node-dbf-proxy#3]
I am trying to use node-dbf-proxy and I am trying to use this with following code
```
`var DBF  = require('dbf-proxy');
var path = require('path');
console.log(path.join('C:', 'data'));

db = new DBF("C:\\data");
console.log(db);
db.query('SELECT * FROM user', ( err, data ) =>{
  console.log(err);
});`
```
and getting error as below:

`C:\data
DBFProxy {
  _path: 'C:\\data',
  _binary: 'C:\\workspace\\Personal\\practice\\siba\\node_modules\\dbf-proxy\\bin\\dbf.exe'
}

Unhandled Exception: System.InvalidOperationException: The 'VFPOLEDB.1' provider is not registered on the local machine.
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)       
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)     
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory 
connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at dbf.Program.Main(String[] args)`
Could you please help me to resolve this?

**Comment by rabrux** [comment]
i do not remember this project anymore but i think that you need to install the odbc driver for vfpro 9
